### ISSUE TITLE
Support for HAL Hypertext Cache Pattern

### ISSUE THREAD

**Issue by nlenoire** [LuvDaSun/angular-hal#60] opened 2016-06-20 13:11 UTC
Hello,

I'm currently using an old version of angular-hal (0.1.5) in my project, but I plan to upgrade to new version soon.
However, it looks to me that if the old version of angular-hal was well supporting the Hypertext cache patter (see section 8.3 of the HAL specification), that is not the case of the new version as far as I understood new source code (sorry, I didn't yet take the time to write a test for this).

Typically, I have this kind of representation:
```
{
   "_link": {
      "self": {
         href: "http://my/rest/api"
     },
     "item": {
        "href": "http://my/rest/api/{itemId},
        "templated": true
     }
   },
   "_embedded": { 
      "item": [
      {
         "_links": {
            "self": {
               "href": "http://my/rest/api/item-001"
            },
            "itemId": "item-001"
         } 
      },
      {
         "_links": {
            "self": {
               "href": "http://my/rest/api/item-002"
            },
            "itemId": "item-002"
      }]
   }
}
```
If I far as I can understand, if I call `resource.$request().$get('item', {itemId: 'item-003'}, {})`, I will not obtain the resource representation of item-003, but the list of all embedded items, related by the rel 'item' from the root resource.

Could you please let me know if my assumption is wrong?

Thanks,
-NL

**Comment by maennchen** [comment] 2016-06-20 13:16
Hi NL,

Yes, currently there is no caching implemented. I'd be happy to merge a PR though.

I think if you run this code right now, you'll get a list of items (the embedded ones). If you can confirm that, I'd open a bug.

**Comment by maennchen** [comment] 2016-06-20 13:29
Hi again,

I took time to read what § 8.3 exactly is. We do have support for that.

Look here:
https://github.com/LuvDaSun/angular-hal/blob/master/src/resource/hal-resource-client.factory.js#L59-L71

I however think that it'll misbehave if you specify url parameters.

**Comment by nlenoire** [comment] 2016-06-20 13:40
I think we reached to the same conclusion.

**Comment by maennchen** [comment] 2016-06-20 13:43
Hmm. Would you say that this is the expected behaviour:?

 * `resource.$request().$get('item', {some: 'url parameter'})` - Do HTTP Request
 * `resource.$request().$get('item')` - Use Embedded

**Comment by nlenoire** [comment] 2016-06-20 14:07
More precisely:
* `resource.$request().$get('item', {some: 'url parameter'}) - Lookup from embedded first, Do HTTP Request if not found
* `resource.$request().$get('item') - Use Embedded

However, keep in mind that I used $get as an example, but it could be any http verb. (this make me remember that I also noticed you now iterate over embedded resources to perform request of any kind of http verb, which is maybe not what should be done. Maybe another issue.)

**Comment by nlenoire** [comment] 2016-06-20 14:29
You should look at v0.1.5 in callLink function.

**Comment by maennchen** [comment] 2016-06-20 14:32
Method: `if (method === 'GET') {` https://github.com/LuvDaSun/angular-hal/blob/v0.1.5/angular-hal.js#L148

I don't think that ignoring the url params is a good idea though if embedded exists.

**Comment by nlenoire** [comment] 2016-06-20 14:49
I'm not sure to get your point. Why do you say url params are ignored?

**Comment by maennchen** [comment] 2016-06-20 14:50
If the `callLink` function exits here, what is done with the `params` argument of the function?

**Comment by nlenoire** [comment] 2016-06-20 15:11
Humm, I think you raise a good point... 

`params` are used to resolve the actual link href just the line above using function `hrefLink`. For each embedded resource a corresponding link is created. But you maybe right that then actual templated link definition maybe lost as per 0.1.5 implementation...

I think I need to test this more.

Thanks for your fast answers

**Comment by maennchen** [comment] 2016-06-20 16:58
@nlenoire: Could you write a test that fails if you come to the conclusion that the library doesn't behave like it should?

I'll close the issue for now since I'm not sure if we have a problem or not.

**Closed by maennchen** 2016-06-20 16:58 UTC
