### ISSUE TITLE
how to update existing Resource

### ISSUE THREAD

**Issue by francescobragagna** [LuvDaSun/angular-hal#64] opened 2016-07-08 07:40 UTC
This is a question, for a clarification.

I get a Resource from server, and I would like to update it.
Looking the source code if I understood well the Resources are created with not configurable fields.
How should I do to change a Resource attribute and send it back to the server, as updated? 

E.g.:
$http({url: '/message/23'}).then(function(message){
     message.text = 'new Text';  //I cant't ! <<<<<<<<
     message.$post();
});

I would like to above to try to clone the resource, or make a copy with configurable attribute... 
I can't understand if I should use $response() or any other method. 

Thanks

Francesco

**Comment by maennchen** [comment] 2016-07-08 07:53
Resources are not mutable by design.

Your code should look like this:

```
$http({url: '/message/23'})
  .then((message) => {
    return message.$request().$post('self', {}, {
      text: 'New Text',
    });
  })
  .then(() => {
    console.log('Saved');
  })
  .catch((error) => {
    console.error(error);
  });
```

**Comment by maennchen** [comment] 2016-07-08 07:54
If you want to execute HTTP calls, you always have to use `resource.$request().$[http method]`.

You can find the methods here:
https://github.com/LuvDaSun/angular-hal/blob/master/src/resource/hal-resource-client.factory.js

**Comment by maennchen** [comment] 2016-07-08 07:56
By the way: WHich version of angular-hal are you using? My answer only apply to the latest major release (`>= v2.0.0`)

**Comment by maennchen** [comment] 2016-07-08 07:58
By the way: the Pull Request #63 will add a shorter syntax for HTTP calls on the resource itself. As soon as it is merged, the example code will look like this:

```js
$http({url: '/message/23'})
  .then((message) => {
    return message.$request().$postSelf({
      text: 'New Text',
    });
  })
  .then(() => {
    console.log('Saved');
  })
  .catch((error) => {
    console.error(error);
  });
```

**Comment by francescobragagna** [comment] 2016-07-08 08:16
I will update to major soon. 
I have one questione related. 

In my client angular application, I maintain some resources list, and when i need to change one resource I can use at this point the $postSelf , or $post('self' ... ) 

But after a change like the described above, do you suggest to make an immediately $get, to obtain a new resource changed and replace the old immutable one?  

As client, receiving 200, 201 I exepect the resource is changed as i requested. 
So making a $get just to replace the resource seems to me be onerous.

**Comment by maennchen** [comment] 2016-07-08 11:04
> But after a change like the described above, do you suggest to make an immediately $get, to obtain a new resource changed and replace the old immutable one?

Yes.

> As client, receiving 200, 201 I exepect the resource is changed as i requested. 
So making a $get just to replace the resource seems to me be onerous.

If you need a mutable object, just copy it...

**Closed** 2016-07-08 13:30 UTC
Labels: question
